name: 🚀 Publish to Pub.dev

on:
  push:
    branches: [main]

jobs:
  publishing:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'pub:') }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: Dart and Flutter Package Publisher
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          accessToken: ${{ secrets.ACCESS }}
          refreshToken: ${{ secrets.REFRESH }}
