name: 📝 Versioning

on:
  push:
    branches: [main]

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'pub:') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: "5.10.x"

      - name: Use GitVersion
        uses: gittools/actions/gitversion/execute@v0.9.13
        id: gitversion

      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ steps.gitversion.outputs.NuGetVersionV2 }}
